"""Telegram Bot API /summary handler — SS-TG W6 (env-gated; not the Telethon listener)."""

from __future__ import annotations

import html
import json
import logging
import os
import re
import threading
import time
import urllib.error
import urllib.request
from typing import Any, Dict, Optional

logger = logging.getLogger(__name__)

_POLL_THREAD: Optional[threading.Thread] = None
_STOP = threading.Event()
_RATE_LIMIT_SECONDS = 300
_last_summary_at: Dict[int, float] = {}
_last_command_at: Dict[tuple[str, int], float] = {}
_RUNNING = False

_ENABLED = frozenset({"1", "true", "yes", "on"})
_BOT_COMMANDS = [
    {"command": "start", "description": "Show available commands"},
    {"command": "summary", "description": "Show the 24h subnet pulse"},
    {"command": "trending", "description": "Show trending subnets"},
    {"command": "track", "description": "Track a subnet"},
    {"command": "rank", "description": "Rank a subnet"},
    {"command": "who", "description": "Show an author ranking"},
    {"command": "alerts", "description": "Show or toggle alerts"},
    {"command": "link", "description": "Link Telegram to My Desk"},
]


def summary_bot_enabled() -> bool:
    return os.environ.get("TELEGRAM_SUMMARY_BOT", "off").strip().lower() in _ENABLED


def _bot_token() -> str:
    return os.environ.get("TELEGRAM_BOT_TOKEN", "").strip()


def _desk_url() -> str:
    base = os.environ.get("APP_BASE_URL", "").strip().rstrip("/")
    if base:
        return f"{base}/#section-message-intel"
    return "https://subnet-dashboard.fly.dev/#section-message-intel"


def _telegram_api(method: str, payload: Dict[str, Any], *, timeout: float = 35.0) -> Dict[str, Any]:
    token = _bot_token()
    if not token:
        return {"ok": False, "error": "missing_token"}
    url = f"https://api.telegram.org/bot{token}/{method}"
    body = json.dumps(payload).encode("utf-8")
    req = urllib.request.Request(
        url,
        data=body,
        headers={"Content-Type": "application/json", "User-Agent": "subnet-dashboard-summary-bot"},
        method="POST",
    )
    try:
        with urllib.request.urlopen(req, timeout=timeout) as resp:
            raw = resp.read().decode("utf-8")
            return json.loads(raw) if raw else {"ok": True}
    except urllib.error.HTTPError as exc:
        try:
            detail = exc.read().decode("utf-8")
        except Exception:
            detail = str(exc)
        return {"ok": False, "status": exc.code, "error": detail}
    except Exception as exc:
        return {"ok": False, "error": str(exc)}


def _registry_subnet_names() -> Dict[int, str]:
    from internal.message_intel.engine import _registry_subnet_names

    return _registry_subnet_names()


def _parse_command_text(text: str) -> tuple[str, str]:
    parts = str(text or "").strip().split(maxsplit=1)
    cmd = parts[0].split("@", 1)[0].lower() if parts else ""
    arg = parts[1].strip() if len(parts) > 1 else ""
    return cmd, arg


def _command_rate_limit(key: tuple[str, int], seconds: int = 60) -> Optional[str]:
    now = time.monotonic()
    last = _last_command_at.get(key, 0.0)
    if now - last < seconds:
        return "Please wait a moment before using that command again."
    _last_command_at[key] = now
    return None


def _subnet_from_arg(arg: str) -> Optional[int]:
    m = re.search(r"\b(?:sn|subnet)?\s*(\d+)\b", str(arg or ""), re.IGNORECASE)
    if not m:
        return None
    try:
        return int(m.group(1))
    except ValueError:
        return None


def _format_error(msg: str) -> str:
    return f"<b>Subnet Summers</b>\n\n{msg}"


def _format_help() -> str:
    return (
        "<b>Subnet Summers bot</b>\n\n"
        "/summary [SN] — 24h pulse or subnet summary\n"
        "/trending [1h|24h] — trending subnets\n"
        "/track &lt;SN&gt; — add a subnet to your watchlist\n"
        "/rank &lt;SN&gt; — rank a subnet by Telegram activity\n"
        "/who [author] — show author reliability\n"
        "/alerts — show active alerts\n"
        "/alerts on|off — toggle your alert preference\n"
        "/link &lt;code&gt; — link Telegram to My Desk\n"
        "/link — requires a code generated by My Desk"
    )


def _format_active_alerts() -> str:
    from internal.signals.alerts import AlertEngine

    rows = AlertEngine().recent_alerts(limit=5, active_only=True).get("alerts") or []
    if not rows:
        return "<b>Subnet Summers alerts</b>\n\nNo active alerts right now."
    lines = ["<b>Subnet Summers alerts</b>", ""]
    for row in rows:
        severity = str(row.get("severity") or "info").upper()
        message = str(row.get("message") or row.get("alert_type") or "Alert")
        lines.append(f"• [{severity}] {message}")
    return "\n".join(lines)


def _format_trending(items: list[Dict[str, Any]], window: str) -> str:
    lines = [f"<b>ChatterPower Trending — {window}</b>", ""]
    if not items:
        lines.append("No trending subnets found in that window.")
    for row in items[:5]:
        lines.append(
            f"• SN{row.get('netuid')} {row.get('name') or ''} "
            f"({row.get('mentions', 0)} mentions, power {row.get('chatter_power', 0)})"
        )
    return "\n".join(lines)


def _format_summary_reply(db=None) -> str:
    return build_summary_text(db=db)


def _format_subnet_summary_reply(netuid: int, db=None) -> str:
    from internal.message_intel.rollup import build_subnet_telegram_conviction

    payload = build_subnet_telegram_conviction(netuid=netuid, limit=1, db=db)
    item = next((row for row in payload.get("items") or [] if int(row.get("netuid") or 0) == int(netuid)), None)
    if not item or not item.get("current_calls"):
        return _format_error(f"No recent qualified Telegram calls for SN{netuid}.")
    label = item.get("label") or "mixed"
    lines = [
        f"<b>SN{netuid} Telegram summary</b>",
        "",
        f"Current read: {label} · {item.get('call_count', 0)} calls from {item.get('contributor_count', 0)} contributors",
    ]
    for call in (item.get("current_calls") or [])[:3]:
        direction = str(call.get("direction") or "neutral").upper()
        snippet = str(call.get("content") or "").strip().replace("<", "&lt;").replace(">", "&gt;")
        if len(snippet) > 140:
            snippet = snippet[:137].rstrip() + "…"
        lines.append(f"• {direction} — {snippet or 'call recorded'}")
    lines.extend(["", "Evidence-qualified community commentary; not financial advice."])
    return "\n".join(lines)


def _format_rank(item: Dict[str, Any]) -> str:
    if not item:
        return _format_error("No matching subnet found.")
    return (
        f"<b>Subnet Rank — SN{item.get('netuid')}</b>\n\n"
        f"{item.get('name') or ''}\n"
        f"Mentions: {item.get('mentions', 0)}\n"
        f"ChatterPower: {item.get('chatter_power', 0)}\n"
        f"Why: {item.get('why') or 'n/a'}"
    )


def _format_author(item: Dict[str, Any]) -> str:
    if not item:
        return _format_error("No matching author found.")
    return (
        f"<b>Author Leaderboard</b>\n\n"
        f"{item.get('author_name') or item.get('author_id')}\n"
        f"Messages: {item.get('message_count', 0)}\n"
        f"Accuracy: {item.get('accuracy_pct') if item.get('accuracy_pct') is not None else 'n/a'}"
    )


def _watchlist_load(owner=None):
    from internal.watchlist.store import load_watchlist

    return load_watchlist() if owner is None else load_watchlist(owner=owner)


def _watchlist_save(netuids, thresholds=None, alerts=None, owner=None):
    from internal.watchlist.store import save_watchlist

    if owner is None:
        return save_watchlist(netuids, thresholds=thresholds, alerts=alerts)
    return save_watchlist(netuids, thresholds=thresholds, alerts=alerts, owner=owner)


def _stable_telegram_user(message: Dict[str, Any]) -> str:
    from internal.message_intel.proof import stable_author_id

    return stable_author_id(message)


def _telegram_watchlist_owner(message: Optional[Dict[str, Any]]) -> Optional[str]:
    if not isinstance(message, dict):
        return None
    telegram_owner = f"telegram:{_stable_telegram_user(message)}"
    from internal.watchlist.store import linked_owner

    return linked_owner(telegram_owner) or telegram_owner


def format_summary_message(summary: Dict[str, Any], *, desk_url: Optional[str] = None) -> str:
    """Render build_24h_summary dict as Telegram HTML."""
    desk = desk_url or _desk_url()
    if not summary.get("ready"):
        count = int(summary.get("message_count") or 0)
        need = int(summary.get("min_messages") or 10)
        return (
            f"<b>Subnet Summers — 24h pulse</b>\n\n"
            f"Not enough chatter yet ({count}/{need} messages in 24h).\n"
            f"Check back when the group is active.\n\n"
            f'<a href="{desk}">Open the Subnet Summers desk</a>'
        )

    lines = [
        "<b>Subnet Summers — 24h pulse</b>",
        "",
        f"Messages: {summary.get('message_count', 0)} · "
        f"High conviction: {summary.get('high_conviction_count', 0)}",
    ]
    top = summary.get("top_subnets") or []
    if top:
        lines.append("")
        lines.append("<b>Top subnets</b>")
        for row in top[:5]:
            name = html.escape(str(row.get("name") or f"SN{row.get('netuid')}"))
            line = f"• SN{row.get('netuid')} {name} ({row.get('mentions', 0)} mentions)"
            context = row.get("mention_context")
            if context:
                context_text = html.escape(str(context).strip())
                line += f"\n  {context_text}"
            lines.append(line)

    movers = [m for m in (summary.get("movers") or []) if int(m.get("change") or 0) != 0][:3]
    if movers:
        lines.append("")
        lines.append("<b>Movers</b> (24h vs prior 24h)")
        for row in movers:
            delta = int(row.get("change") or 0)
            arrow = "↑" if delta > 0 else "↓"
            name = row.get("name") or f"SN{row.get('netuid')}"
            lines.append(f"• SN{row.get('netuid')} {name} {arrow}{abs(delta)}")

    pulse = summary.get("group_pulse") or {}
    if pulse.get("group"):
        lines.append("")
        lines.append(
            f"<b>Group pulse:</b> {pulse['group']} ({pulse.get('top_group_messages', pulse.get('messages', 0))} msgs, "
            f"{pulse.get('groups_active', 1)} active)"
        )
    elif pulse.get("messages"):
        lines.append("")
        lines.append(
            f"<b>Group pulse:</b> {pulse.get('messages', 0)} msgs · "
            f"{pulse.get('sentiment', 'Cautious')} · avg conv {pulse.get('avg_conviction', 0)}%"
        )

    lines.extend(["", f'<a href="{desk}">Open the Subnet Summers desk</a>'])
    return "\n".join(lines)


def build_summary_text(*, db=None) -> str:
    from internal.message_intel.rollup import build_24h_summary

    summary = build_24h_summary(registry_names=_registry_subnet_names(), db=db)
    return format_summary_message(summary)


def _rate_limit_reply(chat_id: int) -> Optional[str]:
    now = time.monotonic()
    last = _last_summary_at.get(chat_id, 0.0)
    elapsed = now - last
    if elapsed < _RATE_LIMIT_SECONDS:
        remaining = int(_RATE_LIMIT_SECONDS - elapsed)
        mins = max(1, (remaining + 59) // 60)
        return f"Rate limited — one /summary every 5 minutes. Try again in ~{mins} min."
    _last_summary_at[chat_id] = now
    return None


def handle_summary_command(chat_id: int, *, db=None) -> tuple[str, bool]:
    """Return (text, rate_limited)."""
    limited = _rate_limit_reply(chat_id)
    if limited:
        return limited, True
    return _format_summary_reply(db=db), False


def handle_command(text: str, *, message: Optional[Dict[str, Any]] = None, db=None) -> Optional[str]:
    cmd, arg = _parse_command_text(text)
    if cmd == "/start":
        return _format_help()
    if cmd == "/summary":
        subnet = _subnet_from_arg(arg)
        if subnet is not None:
            return _format_subnet_summary_reply(subnet, db=db)
        return _format_summary_reply(db=db)
    if cmd == "/trending":
        window = "1h" if arg.strip() == "1h" else "24h"
        from internal.message_intel.rollup import build_trending_subnets

        items = build_trending_subnets(limit=5, rank_hours=1 if window == "1h" else 24, window_hours=24)
        return _format_trending(items, window)
    if cmd == "/track":
        subnet = _subnet_from_arg(arg)
        if subnet is None:
            return _format_error("Usage: /track <subnet>")
        owner = _telegram_watchlist_owner(message)
        watch = _watchlist_load(owner) if owner is not None else _watchlist_load()
        pins = list(watch.get("netuids") or [])
        if subnet not in pins:
            pins.append(subnet)
            if owner is None:
                _watchlist_save(pins, thresholds=watch.get("thresholds") or {}, alerts=watch.get("alerts") or {})
            else:
                _watchlist_save(pins, thresholds=watch.get("thresholds") or {}, alerts=watch.get("alerts") or {}, owner=owner)
        return _format_error(f"Added SN{subnet} to watchlist.")
    if cmd == "/link":
        code = str(arg or "").strip().upper()
        if not code or message is None:
            return _format_error("Usage: /link <code from My Desk>")
        telegram_owner = f"telegram:{_stable_telegram_user(message)}"
        from internal.watchlist.store import claim_link_code

        if not claim_link_code(code, telegram_owner):
            return _format_error("That link code is invalid or already used.")
        return _format_error("Telegram watchlist sync is linked. Your /track and /alerts settings now use My Desk.")
    if cmd == "/rank":
        subnet = _subnet_from_arg(arg)
        from internal.message_intel.rollup import build_trending_subnets

        items = build_trending_subnets(limit=50, rank_hours=1, window_hours=24)
        row = next((r for r in items if subnet is not None and int(r.get("netuid") or 0) == subnet), {})
        return _format_rank(row)
    if cmd == "/who":
        author = arg.strip().lstrip("@")
        from internal.message_intel.rollup import build_author_reliability_rows

        rows = build_author_reliability_rows(days=30, limit=25)
        row = next(
            (
                r
                for r in rows
                if author.lower()
                in {
                    str(r.get("author_name") or "").lower(),
                    str(r.get("author_username") or "").lower().lstrip("@"),
                    str(r.get("author_id") or "").lower(),
                }
            ),
            {},
        )
        return _format_author(row)
    if cmd == "/alerts" and not arg.strip():
        return _format_active_alerts()
    if cmd == "/alerts" and message is not None:
        parts = arg.lower().split()
        if not parts or parts[0] not in {"on", "off"}:
            return _format_error("Usage: /alerts on|off")
        owner = _telegram_watchlist_owner(message)
        watch = _watchlist_load(owner) if owner is not None else _watchlist_load()
        user_key = _stable_telegram_user(message)
        alerts = dict(watch.get("alerts") or {})
        alerts[user_key] = {"enabled": parts[0] == "on"}
        if owner is None:
            _watchlist_save(watch.get("netuids") or [], thresholds=watch.get("thresholds") or {}, alerts=alerts)
        else:
            _watchlist_save(
                watch.get("netuids") or [],
                thresholds=watch.get("thresholds") or {},
                alerts=alerts,
                owner=owner,
            )
        return _format_error(f"Alerts turned {parts[0]} for your Telegram identity.")
    return None


def send_message(chat_id: int, text: str, *, parse_mode: str = "HTML") -> Dict[str, Any]:
    return _telegram_api(
        "sendMessage",
        {"chat_id": chat_id, "text": text, "parse_mode": parse_mode, "disable_web_page_preview": False},
    )


def _process_update(update: Dict[str, Any]) -> None:
    message = update.get("message") or update.get("edited_message")
    if not isinstance(message, dict):
        return
    text = str(message.get("text") or "").strip()
    if not text or not text.split()[0].startswith("/"):
        return
    chat = message.get("chat") or {}
    chat_id = chat.get("id")
    if chat_id is None:
        return
    try:
        chat_id = int(chat_id)
    except (TypeError, ValueError):
        return

    cmd, _ = _parse_command_text(text)
    rate_key = (cmd or "unknown", chat_id)
    limited = _command_rate_limit(rate_key)
    if limited:
        reply = limited
    else:
        reply = handle_command(text, message=message)
    if reply is None:
        return
    resp = send_message(chat_id, reply)
    if not resp.get("ok"):
        logger.warning("summary bot send failed chat=%s: %s", chat_id, resp.get("error") or resp)


def _poll_loop() -> None:
    global _RUNNING
    offset = 0
    _RUNNING = True
    command_registration = _telegram_api(
        "setMyCommands", {"commands": _BOT_COMMANDS}, timeout=15.0
    )
    if not command_registration.get("ok"):
        logger.warning(
            "Telegram summary bot command registration failed: %s",
            command_registration.get("error") or command_registration,
        )
    logger.info("Telegram summary bot polling started")
    while not _STOP.is_set():
        resp = _telegram_api(
            "getUpdates",
            {"offset": offset, "timeout": 25, "allowed_updates": ["message", "edited_message"]},
            timeout=35.0,
        )
        if not resp.get("ok"):
            logger.warning("summary bot getUpdates failed: %s", resp.get("error") or resp)
            if _STOP.wait(5):
                break
            continue
        for update in resp.get("result") or []:
            if not isinstance(update, dict):
                continue
            offset = int(update.get("update_id", offset)) + 1
            try:
                _process_update(update)
            except Exception as exc:
                logger.warning("summary bot update failed: %s", exc)
    _RUNNING = False
    logger.info("Telegram summary bot polling stopped")


def summary_bot_running() -> bool:
    return _RUNNING and _POLL_THREAD is not None and _POLL_THREAD.is_alive()


def start_summary_bot() -> bool:
    """Start Bot API long-poll loop when env-gated and token present."""
    global _POLL_THREAD
    if not summary_bot_enabled():
        logger.info("Telegram summary bot disabled (TELEGRAM_SUMMARY_BOT=off)")
        return False
    if not _bot_token():
        logger.info("Telegram summary bot skipped — TELEGRAM_BOT_TOKEN not set")
        return False
    if _POLL_THREAD is not None and _POLL_THREAD.is_alive():
        return True

    _STOP.clear()
    _POLL_THREAD = threading.Thread(target=_poll_loop, daemon=True, name="telegram-summary-bot")
    _POLL_THREAD.start()
    return True


def stop_summary_bot() -> None:
    global _POLL_THREAD
    _STOP.set()
    if _POLL_THREAD is not None:
        _POLL_THREAD.join(timeout=8)
        _POLL_THREAD = None
    _STOP.clear()
